### PR TITLE
Update pl.json

### PR DESCRIPTION
**Pull request by Sebek05**

### CODE REVIEW

**Comment by RadRussianRus** [comment]
Thanks! I'm planning to make this process more automatic in future, by fetching translations from Crowdin.

**Comment by Sebek05** [comment]
On Crowdin the translation is done 100%.

**Comment by Sebek05** [comment]
On Crowdin the translation is done 100%.

**Comment by Sebek05** [comment]
On Crowdin the translation is done 100%.

**Comment by RadRussianRus** [comment]
I saw it, thanks!

**Pull request merged**
