### PR TITLE
Make custom text replaces work without replace emoji being enabled

### PR DESCRIPTION
**Pull request by the-blank-x**
Depends on kotatogram/lib_ui#11

### CODE REVIEW

**Comment by ilya-fedin** [comment]
That would make people who don't like text replaces angry I guess :D

**Comment by ilya-fedin** [comment]
I don't think you really need to change lib_ui's API. It would make more sense to replace the array used in setInstantReplaces when the option changes than creating a new weird special-case API.

**Comment by ilya-fedin** [comment]
> Then don't have any text replaces lol

I don't quite understand what you wanted to say

**Comment by ilya-fedin** [comment]
> When you change the replace emoji option it applies instantly without having to reopen kotatogram

The call to setInstantReplaces should effect instantly as well

**Comment by the-blank-x** [comment]
> The call to setInstantReplaces should have effect instantly as well

I don't get what you're saying

**Comment by ilya-fedin** [comment]
Example of what I mean:
```
	Core::App().settings().replaceEmojiValue(
	) | rpl::start_with_next([=](bool replaceEmoji) {
		if (replaceEmoji) {
			text->setInstantReplaces(Ui::InstantReplaces::Default());
		} else {
			text->setInstantReplaces(Kotato::InstantReplaces::TextOnly());
		}
	});

**Comment by ilya-fedin** [comment]
But I still don't think having text-only replaces always is a good idea, I'm pretty sure that would make people angry

**Comment by the-blank-x** [comment]
I want https://github.com/kotatogram/kotatogram-desktop/wiki/Custom-text-replaces to work even if Replace emoji is disabled, if you don't want them you can always remove it from the config

**Comment by ilya-fedin** [comment]
> I want https://github.com/kotatogram/kotatogram-desktop/wiki/Custom-text-replaces to work even if Replace emoji is disabled

Ah. I thought you want these replaces: https://github.com/kotatogram/lib_ui/blob/master/ui/widgets/input_fields.cpp#L917-L924

It seems to me that the proper way would be to have a setInstantReplaces that accepts a rpl::producer. That would allow the set to be changed at any time in runtime then.

**Comment by RadRussianRus** [comment]
I will return to it after next stable release.

**Pull request merged**
